repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-json
    - id: check-added-large-files

- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
  - id: black

- repo: https://github.com/EmbarkStudios/cargo-deny
  rev: 0.14.24
  hooks:
    - id: cargo-deny
      args: ["--all-features", "check"]
