repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: ^charts/.*/README.md
      - id: check-yaml
        exclude: ^charts/
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.14.24
    hooks:
      - id: cargo-deny
        args: ['--all-features', 'check']

  - repo: local
    hooks:
      - id: run-pnpm-script
        name: Pnpm Audit
        entry: pnpm format
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: run-pnpm-script
        name: Format
        entry: pnpm format
        language: system
        pass_filenames: false

  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.13.1
    hooks:
      - id: helm-docs-built
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts
