name: RustCoverage
description: Check for coverage and report the status as a comment on the PR
inputs:
  dashboard:
    description: Whether a dashboard should be created
    required: true
    default: 'false'
  comment:
    description: Whether a comment should be created
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Set code coverage status
      uses: actions/github-script@v7
      with:
        script: |
          const commentBody = `# Code Coverage
          |File|Coverage|Lines|
          |:--|:--|:--|
          |[crates/file/one.rs](https://github.com)|50%|15|
          # Audit
          |Dependency|Level|
          |:--|:--|
          |tokio|Critical|`;

          async function findExistingComment() {
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            console.log(comments)

            // Look for a comment that starts with the first line of our comment body
            return comments.find(comment => comment.body.startsWith('# Code Coverage') && comment.user.login === context.actor);
          }

          async function createOrUpdateComment() {
            const existingComment = await findExistingComment();

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
          }

          createOrUpdateComment().catch(error => {
            console.error(error);
            process.exit(1);
          });
