name: RustCoverage
description: Check for coverage and report the status as a comment on the PR
inputs:
  dashboard:
    description: Whether a dashboard should be created
    required: true
    default: 'false'
  comment:
    description: Whether a comment should be created
    required: true
    default: 'true'
runs:
  using: 'composite'
  steps:
    - name: Hello World
      run: echo HELLO
      shell: bash

    - name: Set code coverage status
      uses: actions/github-script@v6
      with:
        script: |
          const { context } = require('@actions/github');
          const coverage = 90;
          const state = coverage > 80 ? 'success' : 'failure';
          const description = `Code coverage is ${coverage}%`;
          const targetUrl = 'https://your-report-url/';

          await github.repos.createCommitStatus({
            ...context.repo,
            sha: context.sha,
            state: state,
            context: 'code-coverage',
            description: description,
            target_url: targetUrl
          });
