name: 'Test: RustCoverage'

on:
  workflow_dispatch:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.head_ref }}
      - uses: ./actions/rust-coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
